version: "3.1"
services:    
    ofx-import-api:
        container_name: ofx-import-api
        image: ofx-import-api
        restart: always
        networks:
            - ofx-import-network
        environment:
            ASPNETCORE_ENVIRONMENT: "Development"
        build:
            context: ../SRC/
            dockerfile: OfxImports/Dockerfile
        ports:
            - "5033:80"
        depends_on:
            - pgsql-data
        links:
            - pgsql-data      
    pgsql-data:
        container_name: pgsql-data
        image: postgres:12
        networks:
            - ofx-import-network
        volumes:
            - ./database/pgsql/data:/var/lib/postgresql
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: pguser
            POSTGRES_PASSWORD: "cmsol@strongpass!123"
            POSTGRES_DB: poll-pgsql    
networks:
  ofx-import-network:
    driver: bridge
