version: "3.1"
services:        
    pgsql-data:
        container_name: pgsql-data
        image: postgres:12
        networks:
            - ofx-import-network
        volumes:
            - ./database/pgsql/data:/var/lib/postgresql
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: pguser
            POSTGRES_PASSWORD: "cmsol@strongpass!123"
            POSTGRES_DB: ofximports-pgsql    
networks:
  ofx-import-network:
    driver: bridge
